services:
  - type: web
    name: english-app-backend
    env: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FIREBASE_CONFIG
        sync: false
      - key: ACCESS_SECRET
        sync: false
      - key: REFRESH_SECRET
        sync: false
